### ISSUE TITLE
Incorrect sampling of `sigma1` and `sigma0` in XBCF Discrete

### ISSUE THREAD

**Issue by andrewherren** [JingyuHe/XBART#137]
Here is a script (albeit in my fork which has a few other changes) that produces this issue, even with the original `XBCF.discrete` (not my modified method): https://github.com/andrewherren/XBART/blob/propensity_trees/tests/xbcf_propensity_shrinkage_debug.R

After running the sampler, `sigma1` is 0 for every sweep and `sigma1` becomes zero after a few dozen iterations.

**Comment by andrewherren** [comment]
A replication script is now available in the linked PR (`tests/debug_XBCF_discrete.R`)

**Comment by MaggieWang0614** [comment]
Hi Drew, thanks for bringing it up. I've fixed the bug. Now closing the issue.
